function plotresults(TestLabels, prePARA, maxbp, minbp, maxhr, minhr)
%CREATEFIGURE(YMATRIX1)
%  YMATRIX1:  matrix of y data

%  Auto-generated by MATLAB on 01-Aug-2014 16:52:53

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1,'YGrid','on');
box(axes1,'on');
hold(axes1,'all');

if min(size(TestLabels)) >= 3
    snum = length(TestLabels(1,:));
    TrueBP = TestLabels(1:2,:) * maxbp + minbp;
    preBP = prePARA(1:2,:) * maxbp + minbp;
    strSBP = measurement(TrueBP(1,:)', preBP(1,:)');
    strDBP = measurement(TrueBP(2,:)', preBP(2,:)');
    str = {'SBP, ' strSBP;'DBP, ' strDBP};
    TrueBP = TrueBP';
    preBP = preBP';
    BP = ([preBP(1:snum,:) TrueBP(1:snum,:)]);
    % Create multiple lines using matrix input to plot
    plot1 = plot(BP,'Parent',axes1,'LineWidth',2);
    %     set(plot1(1),'Marker','square','DisplayName','True SBP');
    %     set(plot1(2),'MarkerSize',10,'Marker','x','DisplayName','True DBP');
    %     set(plot1(3),'Marker','o','Color',[1 0 0],'DisplayName','Estimated SBP');
    %     set(plot1(4),'Marker','v','DisplayName','Estimated DBP');
    set(plot1(1),...
        'Color',[0.501960813999176 0.501960813999176 0.501960813999176],...
        'DisplayName','Estimated SBP');
    set(plot1(2),...
        'Color',[0.0431372560560703 0.517647087574005 0.780392169952393],...
        'DisplayName','Estimated DBP');
    set(plot1(3),'Color',[1 0 0],'DisplayName','True SBP');
    set(plot1(4),'Color',[0 1 0],'DisplayName','True DBP');
    title(str);
    % Create legend
    legend(axes1,'show');
    
    
    figure1 = figure;
    % Create axes
    axes1 = axes('Parent',figure1,'YGrid','on');
    box(axes1,'on');
    hold(axes1,'all');
    TrueHR = TestLabels(3,:) * maxhr + minhr;
    preHR = prePARA(3,:) * maxhr + minhr;
    strHR = measurement(TrueHR(:), preHR(:));
    str = ['HR, ' strHR];
    TrueHR = TrueHR';
    preHR = preHR';
    HR = ([preHR(1:snum,:) TrueHR(1:snum,:)]);
    % Create multiple lines using matrix input to plot
    plot1 = plot(HR,'Parent',axes1,'LineWidth',2);
    set(plot1(1),...
        'Color',[0.501960813999176 0.501960813999176 0.501960813999176],...
        'DisplayName','Estimated HR');
    set(plot1(2),'Color',[1 0 0],'DisplayName','True HR');
    title(str);
    % Create legend
    legend(axes1,'show');
    
    figure;
    subplot(1,3,1);scatter(TrueBP(:,1),preBP(:,1));title('SBP');
    subplot(1,3,2);scatter(TrueBP(:,2),preBP(:,2));title('DBP');
    subplot(1,3,3);scatter(TrueHR, preHR);title('HR');
elseif min(size(TestLabels)) == 2
    snum = length(TestLabels(1,:));
    TrueBP = TestLabels(1:2,:) * maxbp + minbp;
    preBP = prePARA(1:2,:) * maxbp + minbp;
    strSBP = measurement(TrueBP(1,:)', preBP(1,:)');
    strDBP = measurement(TrueBP(2,:)', preBP(2,:)');
    str = {'SBP, ' strSBP;'DBP, ' strDBP};
    TrueBP = TrueBP';
    preBP = preBP';
    BP = ([TrueBP(1:snum,:) preBP(1:snum,:)]);
    % Create multiple lines using matrix input to plot
    plot1 = plot(BP,'Parent',axes1,'LineWidth',2);
    %     set(plot1(1),'Marker','square','DisplayName','True SBP');
    %     set(plot1(2),'MarkerSize',10,'Marker','x','DisplayName','True DBP');
    %     set(plot1(3),'Marker','o','Color',[1 0 0],'DisplayName','Estimated SBP');
    %     set(plot1(4),'Marker','v','DisplayName','Estimated DBP');
    set(plot1(1),'DisplayName','True SBP');
    set(plot1(2),'DisplayName','True DBP');
    set(plot1(3),'Color',[1 0 0],'DisplayName','Estimated SBP');
    set(plot1(4),'DisplayName','Estimated DBP');
    title(str);
    % Create legend
    legend(axes1,'show');
    
    figure;
    subplot(1,2,1);scatter(TrueBP(:,1),preBP(:,1));title('SBP');
    subplot(1,2,2);scatter(TrueBP(:,2),preBP(:,2));title('DBP');
elseif min(size(TestLabels)) == 1
    snum = length(TestLabels);
    TrueHR = TestLabels * maxhr + minhr;
    preHR = prePARA * maxhr + minhr;
    strHR = measurement(TrueHR(:), preHR(:));
    str = ['HR, ' strHR];
    TrueHR = TrueHR';
    preHR = preHR';
    HR = ([TrueHR(1:snum,:) preHR(1:snum,:)]);
    % Create multiple lines using matrix input to plot
    plot1 = plot(HR,'Parent',axes1,'LineWidth',2);
    set(plot1(1),'Marker','square','DisplayName','True HR');
    set(plot1(2),'Marker','o','Color',[1 0 0],'DisplayName','Estimated HR');
    title(str);
    % Create legend
    legend(axes1,'show');
    
    figure;
    scatter(TrueHR, preHR);title('HR');
end
end

